# Generated by Django 5.1.2 on 2024-10-09 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_lat', models.FloatField()),
                ('source_lng', models.FloatField()),
                ('dest_lat', models.FloatField()),
                ('dest_lng', models.FloatField()),
                ('source_address', models.CharField(max_length=255)),
                ('destination_address', models.CharField(max_length=255)),
                ('search_date', models.DateField()),
                ('search_time', models.TimeField()),
                ('distance', models.FloatField()),
                ('duration', models.FloatField()),
                ('carbon_footprint', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
